import json

movies = [
    {"year": 2023, "title": "オッペンハイマー"},
    {"year": 2022, "title": "エブリシング・エブリウェア・オール・アット・ワンス"},
    {"year": 2021, "title": "コーダ あいのうた"},
    {"year": 2020, "title": "ノマドランド"},
    {"year": 2019, "title": "パラサイト 半地下の家族"},
    {"year": 2018, "title": "グリーンブック"},
    {"year": 2017, "title": "シェイプ・オブ・ウォーター"},
    {"year": 2016, "title": "ムーンライト"},
    {"year": 2015, "title": "スポットライト 世紀のスクープ"},
    {"year": 2014, "title": "バードマン あるいは（無知がもたらす予期せぬ奇跡）"},
    {"year": 2013, "title": "それでも夜は明ける"},
    {"year": 2012, "title": "アルゴ"},
    {"year": 2011, "title": "アーティスト"},
    {"year": 2010, "title": "英国王のスピーチ"},
    {"year": 2009, "title": "ハート・ロッカー"},
    {"year": 2008, "title": "スラムドッグ$ミリオネア"},
    {"year": 2007, "title": "ノーカントリー"},
    {"year": 2006, "title": "ディパーテッド"},
    {"year": 2005, "title": "クラッシュ"},
    {"year": 2004, "title": "ミリオンダラー・ベイビー"},
    {"year": 2003, "title": "ロード・オブ・ザ・リング/王の帰還"},
    {"year": 2002, "title": "シカゴ"},
    {"year": 2001, "title": "ビューティフル・マインド"},
    {"year": 2000, "title": "グラディエーター"},
    {"year": 1999, "title": "アメリカン・ビューティー"},
    {"year": 1998, "title": "恋におちたシェイクスピア"},
    {"year": 1997, "title": "タイタニック"},
    {"year": 1996, "title": "イングリッシュ・ペイシェント"},
    {"year": 1995, "title": "ブレイブハート"},
    {"year": 1994, "title": "フォレスト・ガンプ/一期一会"},
    {"year": 1993, "title": "シンドラーのリスト"},
    {"year": 1992, "title": "許されざる者"},
    {"year": 1991, "title": "羊たちの沈黙"},
    {"year": 1990, "title": "ダンス・ウィズ・ウルブズ"},
    {"year": 1989, "title": "ドライビング Miss デイジー"},
    {"year": 1988, "title": "レインマン"},
    {"year": 1987, "title": "ラストエンペラー"},
    {"year": 1986, "title": "プラトーン"},
    {"year": 1985, "title": "愛と哀しみの果て"},
    {"year": 1984, "title": "アマデウス"},
    {"year": 1983, "title": "愛と追憶の日々"},
    {"year": 1982, "title": "ガンジー"},
    {"year": 1981, "title": "炎のランナー"},
    {"year": 1980, "title": "普通の人々"},
    {"year": 1979, "title": "クレイマー、クレイマー"},
    {"year": 1978, "title": "ディア・ハンター"},
    {"year": 1977, "title": "アニー・ホール"},
    {"year": 1976, "title": "ロッキー"},
    {"year": 1975, "title": "カッコーの巣の上で"},
    {"year": 1974, "title": "ゴッドファーザー PART II"},
    {"year": 1973, "title": "スティング"},
    {"year": 1972, "title": "ゴッドファーザー"},
    {"year": 1971, "title": "フレンチ・コネクション"},
    {"year": 1970, "title": "パットン大戦車軍団"},
    {"year": 1969, "title": "真夜中のカーボーイ"},
    {"year": 1968, "title": "オリバー!"},
    {"year": 1967, "title": "夜の大捜査線"},
    {"year": 1966, "title": "わが命つきるとも"},
    {"year": 1965, "title": "サウンド・オブ・ミュージック"},
    {"year": 1964, "title": "マイ・フェア・レディ"},
    {"year": 1963, "title": "トム・ジョーンズの華麗な冒険"},
    {"year": 1962, "title": "アラビアのロレンス"},
    {"year": 1961, "title": "ウエスト・サイド物語"},
    {"year": 1960, "title": "アパートの鍵貸します"},
    {"year": 1959, "title": "ベン・ハー"},
    {"year": 1958, "title": "恋の手ほどき"},
    {"year": 1957, "title": "戦場にかける橋"},
    {"year": 1956, "title": "80日間世界一周"},
    {"year": 1955, "title": "マーティ"},
    {"year": 1954, "title": "波止場"},
    {"year": 1953, "title": "地上より永遠に"},
    {"year": 1952, "title": "地上最大のショウ"},
    {"year": 1951, "title": "巴里のアメリカ人"},
    {"year": 1950, "title": "イヴの総て"},
    {"year": 1949, "title": "オール・ザ・キングスメン"},
    {"year": 1948, "title": "ハムレット"},
    {"year": 1947, "title": "紳士協定"},
    {"year": 1946, "title": "我等の生涯の最良の年"},
    {"year": 1945, "title": "失われた週末"},
    {"year": 1944, "title": "我が道を往く"},
    {"year": 1943, "title": "カサブランカ"},
    {"year": 1942, "title": "ミニヴァー夫人"},
    {"year": 1941, "title": "わが谷は緑なりき"},
    {"year": 1940, "title": "レベッカ"},
    {"year": 1939, "title": "風と共に去りぬ"},
    {"year": 1938, "title": "我が家の楽園"},
    {"year": 1937, "title": "ゾラの生涯"},
    {"year": 1936, "title": "巨星ジーグフェルド"},
    {"year": 1935, "title": "戦艦バウンティ号の叛乱"},
    {"year": 1934, "title": "或る夜の出来事"},
    {"year": 1933, "title": "カヴァルケード"},
    {"year": 1932, "title": "グランド・ホテル"},
    {"year": 1931, "title": "シマロン"},
    {"year": 1930, "title": "西部戦線異状なし"},
    {"year": 1929, "title": "ブロードウェイ・メロディー"},
    {"year": 1927, "title": "つばさ"}
]

js_content = "const academyWinners = [\n"
for m in movies:
    js_content += f'    {{ year: {m["year"]}, title: "{m["title"]}", eigaScore: "-.-", filmarksScore: "-.-" }},\n'
js_content += "];\n"

with open("js/academy_data.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print("Generated full academy list.")
