const goldenGlobeWinners = [
    { "year": 2026, "title": "ハムネット", "eigaScore": "3.9", "filmarksScore": "4.0" },
    { "year": 2025, "title": "ブルータリスト", "eigaScore": "3.5", "filmarksScore": "3.9" },
    { "year": 2024, "title": "オッペンハイマー", "eigaScore": "3.7", "filmarksScore": "3.9" },
    { "year": 2023, "title": "フェイブルマンズ", "eigaScore": "3.7", "filmarksScore": "3.9" },
    { "year": 2022, "title": "パワー・オブ・ザ・ドッグ", "eigaScore": "3.6", "filmarksScore": "3.8" },
    { "year": 2021, "title": "ノマドランド", "eigaScore": "3.7", "filmarksScore": "3.8" },
    { "year": 2020, "title": "1917 命をかけた伝令", "eigaScore": "3.9", "filmarksScore": "4.0" },
    { "year": 2019, "title": "ボヘミアン・ラプソディ", "eigaScore": "4.2", "filmarksScore": "4.2" },
    { "year": 2018, "title": "スリー・ビルボード", "eigaScore": "3.9", "filmarksScore": "4.0" },
    { "year": 2017, "title": "ムーンライト", "eigaScore": "3.4", "filmarksScore": "2.6" },
    { "year": 2016, "title": "レヴェナント：蘇えりし者", "eigaScore": "3.7", "filmarksScore": "3.8" },
    { "year": 2015, "title": "6才のボクが、大人になるまで。", "eigaScore": "3.8", "filmarksScore": "3.6" },
    { "year": 2014, "title": "それでも夜は明ける", "eigaScore": "3.8", "filmarksScore": "3.8" },
    { "year": 2013, "title": "アルゴ", "eigaScore": "3.9", "filmarksScore": "3.6" },
    { "year": 2012, "title": "ファミリー・ツリー", "eigaScore": "3.7", "filmarksScore": "3.6" },
    { "year": 2011, "title": "ソーシャル・ネットワーク", "eigaScore": "3.7", "filmarksScore": "3.6" },
    { "year": 2010, "title": "アバター", "eigaScore": "3.8", "filmarksScore": "3.6" },
    { "year": 2009, "title": "スラムドッグ$ミリオネア", "eigaScore": "4.0", "filmarksScore": "3.8" },
    { "year": 2008, "title": "つぐない", "eigaScore": "3.8", "filmarksScore": "3.0" },
    { "year": 2007, "title": "バベル", "eigaScore": "3.3", "filmarksScore": "3.8" },
    { "year": 2006, "title": "ブロークバック・マウンテン", "eigaScore": "3.9", "filmarksScore": "3.8" },
    { "year": 2005, "title": "アビエイター", "eigaScore": "3.5", "filmarksScore": "3.4" },
];
